package com.example.ui.screens

import androidx.compose.foundation.background
import androidx.compose.foundation.verticalScroll
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.PasswordVisualTransformation
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.example.data.*
import com.example.ui.components.SimulatedMap
import com.example.viewmodel.TrackerViewModel

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun DriverScreen(
    viewModel: TrackerViewModel,
    modifier: Modifier = Modifier
) {
    val loggedInDriver by viewModel.loggedInDriver.collectAsState()

    Box(
        modifier = modifier
            .fillMaxSize()
            .background(Color(0xFF121212))
            .padding(16.dp)
    ) {
        if (loggedInDriver == null) {
            DriverLoginCard(viewModel)
        } else {
            DriverControlPanel(viewModel, loggedInDriver!!)
        }
    }
}

@Composable
fun DriverLoginCard(viewModel: TrackerViewModel) {
    var username by remember { mutableStateOf("") }
    var password by remember { mutableStateOf("") }
    val loginError by viewModel.loginError.collectAsState()

    Column(
        modifier = Modifier
            .fillMaxSize()
            .verticalScroll(rememberScrollState()),
        horizontalAlignment = Alignment.CenterHorizontally,
        verticalArrangement = Arrangement.Center
    ) {
        Icon(
            imageVector = Icons.Default.AccountCircle,
            contentDescription = "Driver Login",
            tint = Color(0xFFFF9800),
            modifier = Modifier.size(80.dp)
        )

        Spacer(modifier = Modifier.height(16.dp))

        Text(
            text = "Driver Duty Portal",
            color = Color.White,
            style = MaterialTheme.typography.headlineSmall,
            fontWeight = FontWeight.Bold
        )
        Text(
            text = "Enter the login credentials generated by the School Admin to start broadcasting trip telemetry.",
            color = Color.Gray,
            style = MaterialTheme.typography.bodyMedium,
            textAlign = TextAlign.Center,
            modifier = Modifier.padding(horizontal = 16.dp, vertical = 8.dp)
        )

        Spacer(modifier = Modifier.height(16.dp))

        Card(
            colors = CardDefaults.cardColors(containerColor = Color(0xFF1E1E1E)),
            shape = RoundedCornerShape(16.dp),
            modifier = Modifier.fillMaxWidth()
        ) {
            Column(
                modifier = Modifier.padding(20.dp),
                verticalArrangement = Arrangement.spacedBy(16.dp)
            ) {
                if (loginError != null) {
                    Text(
                        text = loginError!!,
                        color = MaterialTheme.colorScheme.error,
                        style = MaterialTheme.typography.bodyMedium,
                        fontWeight = FontWeight.Bold
                    )
                }

                TextField(
                    value = username,
                    onValueChange = { username = it },
                    label = { Text("Username") },
                    colors = TextFieldDefaults.colors(
                        focusedContainerColor = Color(0xFF2C2C2C),
                        unfocusedContainerColor = Color(0xFF2C2C2C)
                    ),
                    modifier = Modifier.fillMaxWidth().testTag("driver_username_field")
                )

                TextField(
                    value = password,
                    onValueChange = { password = it },
                    label = { Text("Password") },
                    visualTransformation = PasswordVisualTransformation(),
                    colors = TextFieldDefaults.colors(
                        focusedContainerColor = Color(0xFF2C2C2C),
                        unfocusedContainerColor = Color(0xFF2C2C2C)
                    ),
                    modifier = Modifier.fillMaxWidth().testTag("driver_password_field")
                )

                Button(
                    onClick = { viewModel.loginDriver(username, password) },
                    colors = ButtonDefaults.buttonColors(containerColor = Color(0xFFFF9800)),
                    modifier = Modifier
                        .fillMaxWidth()
                        .height(50.dp)
                        .testTag("driver_login_btn")
                ) {
                    Text("Access Duty Portal", fontWeight = FontWeight.Bold, fontSize = 15.sp)
                }
            }
        }

        Spacer(modifier = Modifier.height(24.dp))

        // Guide / Tip box
        Card(
            colors = CardDefaults.cardColors(containerColor = Color(0xFF2C1C0D)),
            border = androidx.compose.foundation.BorderStroke(1.dp, Color(0xFFFF9800).copy(alpha = 0.5f)),
            shape = RoundedCornerShape(12.dp),
            modifier = Modifier.fillMaxWidth()
        ) {
            Row(
                modifier = Modifier.padding(14.dp),
                verticalAlignment = Alignment.CenterVertically
            ) {
                Icon(imageVector = Icons.Default.Info, contentDescription = "Info", tint = Color(0xFFFF9800))
                Spacer(modifier = Modifier.width(12.dp))
                Column {
                    Text("Pre-configured Duty Credentials:", color = Color.White, fontWeight = FontWeight.Bold, fontSize = 12.sp)
                    Text("Username: yusuf  |  Password: 123", color = Color.LightGray, fontSize = 11.sp)
                    Text("Username: nabi   |  Password: 123", color = Color.LightGray, fontSize = 11.sp)
                }
            }
        }
    }
}

@Composable
fun DriverControlPanel(viewModel: TrackerViewModel, driver: Driver) {
    val activeTripId by viewModel.activeTripId.collectAsState()
    val buses by viewModel.allBuses.collectAsState()
    val routes by viewModel.allRoutes.collectAsState()

    val mappedBus = buses.find { it.id == driver.mappedBusId }
    val mappedRoute = routes.find { it.id == driver.mappedRouteId }

    var isEditingAssignment by remember { mutableStateOf(false) }

    Column(modifier = Modifier.fillMaxSize()) {
        // Driver Header
        Row(
            modifier = Modifier
                .fillMaxWidth()
                .padding(bottom = 12.dp),
            horizontalArrangement = Arrangement.SpaceBetween,
            verticalAlignment = Alignment.CenterVertically
        ) {
            Column(modifier = Modifier.weight(1f)) {
                Text(
                    text = "Welcome, ${driver.name}",
                    color = Color.White,
                    fontWeight = FontWeight.Bold,
                    fontSize = 18.sp
                )
                Text(
                    text = "Vehicle: ${mappedBus?.plateNumber ?: "Unassigned"} • Route: ${mappedRoute?.routeName ?: "Unassigned"}",
                    color = Color.Gray,
                    fontSize = 12.sp
                )
            }

            Row(verticalAlignment = Alignment.CenterVertically) {
                if (activeTripId == null) {
                    IconButton(
                        onClick = { isEditingAssignment = !isEditingAssignment },
                        modifier = Modifier.testTag("driver_change_assignment_btn")
                    ) {
                        Icon(
                            imageVector = if (isEditingAssignment) Icons.Default.Close else Icons.Default.Edit,
                            contentDescription = "Change Bus/Route",
                            tint = Color(0xFFFF9800)
                        )
                    }
                }

                TextButton(
                    onClick = { viewModel.logoutDriver() },
                    colors = ButtonDefaults.textButtonColors(contentColor = Color.Red)
                ) {
                    Icon(imageVector = Icons.Default.ExitToApp, contentDescription = "Logout")
                    Spacer(modifier = Modifier.width(4.dp))
                    Text("Logout")
                }
            }
        }

        Divider(color = Color.DarkGray, thickness = 1.dp, modifier = Modifier.padding(bottom = 16.dp))

        if (mappedBus == null || mappedRoute == null || isEditingAssignment) {
            DutyAssignmentSelector(
                viewModel = viewModel,
                driver = driver,
                buses = buses,
                routes = routes,
                currentBus = mappedBus,
                currentRoute = mappedRoute,
                onCancel = if (mappedBus != null && mappedRoute != null) {
                    { isEditingAssignment = false }
                } else null,
                onConfirmed = { isEditingAssignment = false }
            )
        } else if (activeTripId == null) {
            // Pre-trip safety checklists screen
            PreTripChecklistPanel(viewModel, mappedBus, mappedRoute)
        } else {
            // Live active trip driving simulator screen
            ActiveSimDriverPanel(viewModel, mappedBus, mappedRoute, activeTripId!!)
        }
    }
}

@Composable
fun DutyAssignmentSelector(
    viewModel: TrackerViewModel,
    driver: Driver,
    buses: List<Bus>,
    routes: List<BusRoute>,
    currentBus: Bus?,
    currentRoute: BusRoute?,
    onCancel: (() -> Unit)? = null,
    onConfirmed: () -> Unit
) {
    var selectedBusId by remember(buses, currentBus) { mutableStateOf(currentBus?.id ?: buses.firstOrNull()?.id) }
    var selectedRouteId by remember(routes, currentRoute) { mutableStateOf(currentRoute?.id ?: routes.firstOrNull()?.id) }

    Column(
        modifier = Modifier
            .fillMaxSize()
            .verticalScroll(rememberScrollState()),
        verticalArrangement = Arrangement.spacedBy(16.dp)
    ) {
        Card(
            colors = CardDefaults.cardColors(containerColor = Color(0xFF1E1E1E)),
            shape = RoundedCornerShape(16.dp),
            modifier = Modifier.fillMaxWidth()
        ) {
            Column(modifier = Modifier.padding(16.dp)) {
                Text(
                    text = "VEHICLE & ROUTE SELECTION",
                    color = Color(0xFFFF9800),
                    fontWeight = FontWeight.Bold,
                    fontSize = 12.sp,
                    letterSpacing = 1.sp
                )
                Text(
                    text = "Select your designated vehicle and route before performing pre-trip checklists and starting telemetry broadcast.",
                    color = Color.Gray,
                    fontSize = 11.sp,
                    modifier = Modifier.padding(top = 2.dp, bottom = 12.dp)
                )

                // Bus Selection
                Text(
                    text = "Select Bus",
                    color = Color.White,
                    fontWeight = FontWeight.Bold,
                    fontSize = 14.sp,
                    modifier = Modifier.padding(vertical = 8.dp)
                )

                if (buses.isEmpty()) {
                    Text("No buses available", color = Color.Gray, fontSize = 12.sp)
                } else {
                    Column(verticalArrangement = Arrangement.spacedBy(8.dp)) {
                        buses.forEach { bus ->
                            val isSelected = selectedBusId == bus.id
                            Card(
                                onClick = { selectedBusId = bus.id },
                                colors = CardDefaults.cardColors(
                                    containerColor = if (isSelected) Color(0xFF2C1C0D) else Color(0xFF2C2C2C)
                                ),
                                border = if (isSelected) androidx.compose.foundation.BorderStroke(1.5.dp, Color(0xFFFF9800)) else null,
                                shape = RoundedCornerShape(12.dp),
                                modifier = Modifier.fillMaxWidth().testTag("bus_select_item_${bus.id}")
                            ) {
                                Row(
                                    modifier = Modifier.padding(12.dp),
                                    verticalAlignment = Alignment.CenterVertically
                                ) {
                                    Icon(
                                        imageVector = Icons.Default.DirectionsBus,
                                        contentDescription = "Bus",
                                        tint = if (isSelected) Color(0xFFFF9800) else Color.Gray,
                                        modifier = Modifier.size(28.dp)
                                    )
                                    Spacer(modifier = Modifier.width(12.dp))
                                    Column(modifier = Modifier.weight(1f)) {
                                        Text(
                                            text = bus.plateNumber,
                                            color = Color.White,
                                            fontWeight = FontWeight.Bold,
                                            fontSize = 14.sp
                                        )
                                        Text(
                                            text = "${bus.model} • Capacity: ${bus.capacity} seats",
                                            color = Color.Gray,
                                            fontSize = 11.sp
                                        )
                                    }
                                    if (isSelected) {
                                        Icon(
                                            imageVector = Icons.Default.CheckCircle,
                                            contentDescription = "Selected",
                                            tint = Color(0xFFFF9800),
                                            modifier = Modifier.size(20.dp)
                                        )
                                    }
                                }
                            }
                        }
                    }
                }

                Spacer(modifier = Modifier.height(16.dp))

                // Route Selection
                Text(
                    text = "Select Route",
                    color = Color.White,
                    fontWeight = FontWeight.Bold,
                    fontSize = 14.sp,
                    modifier = Modifier.padding(vertical = 8.dp)
                )

                if (routes.isEmpty()) {
                    Text("No routes available", color = Color.Gray, fontSize = 12.sp)
                } else {
                    Column(verticalArrangement = Arrangement.spacedBy(8.dp)) {
                        routes.forEach { route ->
                            val isSelected = selectedRouteId == route.id
                            Card(
                                onClick = { selectedRouteId = route.id },
                                colors = CardDefaults.cardColors(
                                    containerColor = if (isSelected) Color(0xFF2C1C0D) else Color(0xFF2C2C2C)
                                ),
                                border = if (isSelected) androidx.compose.foundation.BorderStroke(1.5.dp, Color(0xFFFF9800)) else null,
                                shape = RoundedCornerShape(12.dp),
                                modifier = Modifier.fillMaxWidth().testTag("route_select_item_${route.id}")
                            ) {
                                Row(
                                    modifier = Modifier.padding(12.dp),
                                    verticalAlignment = Alignment.CenterVertically
                                ) {
                                    Icon(
                                        imageVector = Icons.Default.Navigation,
                                        contentDescription = "Route",
                                        tint = if (isSelected) Color(0xFFFF9800) else Color.Gray,
                                        modifier = Modifier.size(28.dp)
                                    )
                                    Spacer(modifier = Modifier.width(12.dp))
                                    Column(modifier = Modifier.weight(1f)) {
                                        Text(
                                            text = route.routeName,
                                            color = Color.White,
                                            fontWeight = FontWeight.Bold,
                                            fontSize = 14.sp
                                        )
                                        Text(
                                            text = "Speed Limit: ${route.speedLimit.toInt()} km/h",
                                            color = Color.Gray,
                                            fontSize = 11.sp
                                        )
                                    }
                                    if (isSelected) {
                                        Icon(
                                            imageVector = Icons.Default.CheckCircle,
                                            contentDescription = "Selected",
                                            tint = Color(0xFFFF9800),
                                            modifier = Modifier.size(20.dp)
                                        )
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }

        // Action Buttons
        Row(
            modifier = Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.spacedBy(12.dp)
        ) {
            if (onCancel != null) {
                OutlinedButton(
                    onClick = onCancel,
                    colors = ButtonDefaults.outlinedButtonColors(contentColor = Color.White),
                    border = androidx.compose.foundation.BorderStroke(1.dp, Color.Gray),
                    modifier = Modifier.weight(1f).height(48.dp)
                ) {
                    Text("Cancel")
                }
            }

            Button(
                enabled = selectedBusId != null && selectedRouteId != null,
                onClick = {
                    if (selectedBusId != null && selectedRouteId != null) {
                        viewModel.updateDriverAssignment(selectedBusId!!, selectedRouteId!!)
                        onConfirmed()
                    }
                },
                colors = ButtonDefaults.buttonColors(containerColor = Color(0xFFFF9800)),
                modifier = Modifier.weight(1f).height(48.dp).testTag("confirm_selection_btn")
            ) {
                Text("Confirm & Set Duty", fontWeight = FontWeight.Bold, fontSize = 13.sp)
            }
        }
    }
}

@Composable
fun PreTripChecklistPanel(viewModel: TrackerViewModel, bus: Bus, route: BusRoute) {
    val checklist by viewModel.checklist.collectAsState()
    val allChecked = checklist.values.all { it }

    Column(
        modifier = Modifier
            .fillMaxSize()
            .verticalScroll(rememberScrollState())
    ) {
        Card(
            colors = CardDefaults.cardColors(containerColor = Color(0xFF1E1E1E)),
            shape = RoundedCornerShape(12.dp)
        ) {
            Column(modifier = Modifier.padding(16.dp)) {
                Text(
                    text = "CBSE & RTO MANDATORY PRE-TRIP VEHICLE CHECKLIST",
                    color = Color(0xFFFF9800),
                    fontWeight = FontWeight.Bold,
                    fontSize = 12.sp,
                    letterSpacing = 1.sp
                )
                Text(
                    text = "For safety compliance, verify and confirm all systems before starting.",
                    color = Color.Gray,
                    fontSize = 11.sp,
                    modifier = Modifier.padding(top = 2.dp, bottom = 12.dp)
                )

                checklist.forEach { (item, checked) ->
                    Row(
                        modifier = Modifier
                            .fillMaxWidth()
                            .padding(vertical = 4.dp),
                        verticalAlignment = Alignment.CenterVertically
                    ) {
                        Checkbox(
                            checked = checked,
                            onCheckedChange = { viewModel.toggleChecklistItem(item) },
                            colors = CheckboxDefaults.colors(checkedColor = Color(0xFFFF9800))
                        )
                        Spacer(modifier = Modifier.width(8.dp))
                        Text(text = item, color = Color.LightGray, fontSize = 14.sp)
                    }
                }
            }
        }

        Spacer(modifier = Modifier.height(24.dp))

        Button(
            enabled = allChecked,
            onClick = {
                viewModel.startTrip(viewModel.loggedInDriver.value!!.id, bus.id, route.id)
            },
            colors = ButtonDefaults.buttonColors(
                containerColor = Color(0xFFFF9800),
                disabledContainerColor = Color.DarkGray
            ),
            modifier = Modifier
                .fillMaxWidth()
                .height(56.dp)
                .testTag("start_trip_btn")
        ) {
            Icon(imageVector = Icons.Default.PlayArrow, contentDescription = "Start Trip")
            Spacer(modifier = Modifier.width(8.dp))
            Text(
                text = if (allChecked) "START TRIP & BROADCAST LOCATION" else "COMPLETE SAFETY CHECKLIST TO START",
                fontWeight = FontWeight.Bold,
                fontSize = 13.sp
            )
        }
    }
}

@Composable
fun ActiveSimDriverPanel(viewModel: TrackerViewModel, bus: Bus, route: BusRoute, tripId: Int) {
    val currentTrip by viewModel.currentTrip.collectAsState()
    val stops by viewModel.routeStops.collectAsState()

    val simSpeed by viewModel.simSpeedSlider.collectAsState()
    val simIsDeviated by viewModel.simIsDeviated.collectAsState()
    val waitingAtStop by viewModel.waitingAtStop.collectAsState()

    val latenessTimerActive by viewModel.parentLatenessTimerActive.collectAsState()
    val latenessSec by viewModel.parentLatenessSeconds.collectAsState()
    val tripResumed by viewModel.tripResumed.collectAsState()

    Column(modifier = Modifier.fillMaxSize()) {
        if (tripResumed) {
            Card(
                colors = CardDefaults.cardColors(containerColor = Color(0xFF1B5E20)),
                shape = RoundedCornerShape(8.dp),
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(bottom = 12.dp)
                    .testTag("resumed_trip_banner")
            ) {
                Row(
                    modifier = Modifier.padding(10.dp),
                    verticalAlignment = Alignment.CenterVertically
                ) {
                    Icon(
                        imageVector = Icons.Default.CheckCircle,
                        contentDescription = "Resumed Icon",
                        tint = Color.Green,
                        modifier = Modifier.size(18.dp)
                    )
                    Spacer(modifier = Modifier.width(8.dp))
                    Text(
                        text = "Trip Resumed: Active trip tracking restored successfully!",
                        color = Color.White,
                        fontSize = 12.sp,
                        fontWeight = FontWeight.SemiBold
                    )
                }
            }
        }

        Card(
            colors = CardDefaults.cardColors(containerColor = Color(0xFF1E1E1E)),
            shape = RoundedCornerShape(12.dp),
            modifier = Modifier.padding(bottom = 12.dp)
        ) {
            Row(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(12.dp),
                horizontalArrangement = Arrangement.SpaceBetween,
                verticalAlignment = Alignment.CenterVertically
            ) {
                Row(verticalAlignment = Alignment.CenterVertically) {
                    Box(
                        modifier = Modifier
                            .size(10.dp)
                            .clip(RoundedCornerShape(5.dp))
                            .background(Color.Green)
                    )
                    Spacer(modifier = Modifier.width(8.dp))
                    Text("ACTIVE TRIP ID: #$tripId", color = Color.LightGray, fontWeight = FontWeight.Bold, fontSize = 12.sp)
                }

                Button(
                    onClick = { viewModel.completeTrip() },
                    colors = ButtonDefaults.buttonColors(containerColor = Color(0xFFC62828)),
                    modifier = Modifier
                        .height(36.dp)
                        .testTag("end_trip_btn")
                ) {
                    Text("End Trip", fontSize = 12.sp, fontWeight = FontWeight.Bold)
                }
            }
        }

        // Live visual map feedback
        Text(
            text = "Driver View Navigation Map",
            color = Color.Gray,
            fontWeight = FontWeight.Bold,
            fontSize = 11.sp,
            modifier = Modifier.padding(bottom = 6.dp)
        )

        SimulatedMap(trip = currentTrip, stops = stops)

        Spacer(modifier = Modifier.height(14.dp))

        // Driver Actions and Overrides Panel
        Card(
            colors = CardDefaults.cardColors(containerColor = Color(0xFF1E1E1E)),
            shape = RoundedCornerShape(16.dp),
            modifier = Modifier.weight(1f)
        ) {
            LazyColumn(
                modifier = Modifier
                    .fillMaxSize()
                    .padding(16.dp),
                verticalArrangement = Arrangement.spacedBy(12.dp)
            ) {
                // Arrived at stop handler
                if (waitingAtStop) {
                    val stopName = stops.getOrNull(currentTrip?.currentStopIndex ?: 0)?.stopName ?: "Destination Stop"
                    item {
                        Card(
                            colors = CardDefaults.cardColors(containerColor = Color(0xFF163220)),
                            border = androidx.compose.foundation.BorderStroke(1.dp, Color.Green.copy(alpha = 0.5f)),
                            shape = RoundedCornerShape(12.dp),
                            modifier = Modifier.fillMaxWidth()
                        ) {
                            Column(modifier = Modifier.padding(14.dp)) {
                                Row(verticalAlignment = Alignment.CenterVertically) {
                                    Icon(imageVector = Icons.Default.PushPin, contentDescription = "Arrived", tint = Color.Green)
                                    Spacer(modifier = Modifier.width(8.dp))
                                    Text(
                                        text = "Arrived at Stop: $stopName",
                                        color = Color.White,
                                        fontWeight = FontWeight.Bold,
                                        fontSize = 14.sp
                                    )
                                }

                                Spacer(modifier = Modifier.height(10.dp))

                                if (!latenessTimerActive) {
                                    Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                                        Button(
                                            onClick = { viewModel.parentArrivedAndResume() },
                                            colors = ButtonDefaults.buttonColors(containerColor = Color(0xFF2E7D32)),
                                            modifier = Modifier.weight(1f)
                                        ) {
                                            Text("Parents Present", fontWeight = FontWeight.Bold, fontSize = 12.sp)
                                        }

                                        Button(
                                            onClick = { viewModel.triggerParentLatenessStart() },
                                            colors = ButtonDefaults.buttonColors(containerColor = Color(0xFFC62828)),
                                            modifier = Modifier.weight(1f)
                                        ) {
                                            Text("Parent is Late!", fontWeight = FontWeight.Bold, fontSize = 12.sp)
                                        }
                                    }
                                } else {
                                    Column(
                                        horizontalAlignment = Alignment.CenterHorizontally,
                                        modifier = Modifier.fillMaxWidth()
                                    ) {
                                        Text(
                                            text = "Calculating Parent Lateness...",
                                            color = Color.LightGray,
                                            fontSize = 11.sp
                                        )
                                        val minutesLate = (latenessSec * 0.5)
                                        Text(
                                            text = "DELAY: ${String.format("%.1f", minutesLate)} mins",
                                            color = Color(0xFFE53935),
                                            fontWeight = FontWeight.Bold,
                                            fontSize = 18.sp,
                                            modifier = Modifier.padding(vertical = 4.dp)
                                        )
                                        Button(
                                            onClick = { viewModel.parentArrivedAndResume() },
                                            colors = ButtonDefaults.buttonColors(containerColor = Color(0xFFFF9800)),
                                            modifier = Modifier.fillMaxWidth()
                                        ) {
                                            Text("Parent Arrived • Resume Driving", fontWeight = FontWeight.Bold, fontSize = 12.sp)
                                        }
                                    }
                                }
                            }
                        }
                    }
                }

                // Speed Limit Controller
                item {
                    Column(modifier = Modifier.fillMaxWidth()) {
                        Row(
                            modifier = Modifier.fillMaxWidth(),
                            horizontalArrangement = Arrangement.SpaceBetween,
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            Text(
                                text = "Bus Speed Controller (Telemetry)",
                                color = Color.White,
                                fontWeight = FontWeight.Bold,
                                fontSize = 13.sp
                            )
                            val limit = route.speedLimit
                            Text(
                                text = "${simSpeed.toInt()} km/h (Limit: ${limit.toInt()})",
                                color = if (simSpeed > limit) Color(0xFFE53935) else Color(0xFFFF9800),
                                fontWeight = FontWeight.Bold,
                                fontSize = 14.sp
                            )
                        }

                        Slider(
                            value = simSpeed.toFloat(),
                            onValueChange = { viewModel.setSimSpeed(it.toDouble()) },
                            valueRange = 10f..85f,
                            colors = SliderDefaults.colors(
                                thumbColor = Color(0xFFFF9800),
                                activeTrackColor = Color(0xFFFF9800)
                            ),
                            modifier = Modifier.testTag("driver_speed_slider")
                        )

                        Text(
                            text = "Slide above ${route.speedLimit.toInt()} km/h to trigger real-time speed violation alerts and log records.",
                            color = Color.Gray,
                            fontSize = 10.sp
                        )
                    }
                }

                // Route Deviation Simulation
                item {
                    Row(
                        modifier = Modifier
                            .fillMaxWidth()
                            .clip(RoundedCornerShape(12.dp))
                            .background(Color(0xFF241F20))
                            .padding(12.dp),
                        horizontalArrangement = Arrangement.SpaceBetween,
                        verticalAlignment = Alignment.CenterVertically
                    ) {
                        Column(modifier = Modifier.weight(1f)) {
                            Text(
                                text = "Simulate Route Deviation",
                                color = Color.White,
                                fontWeight = FontWeight.Bold,
                                fontSize = 13.sp
                            )
                            Text(
                                text = "Steers the bus off-path on the maps to test compliance alarms.",
                                color = Color.Gray,
                                fontSize = 10.sp
                            )
                        }

                        Switch(
                            checked = simIsDeviated,
                            onCheckedChange = { viewModel.setSimDeviated(it) },
                            colors = SwitchDefaults.colors(checkedThumbColor = Color(0xFFFF9800)),
                            modifier = Modifier.testTag("driver_deviation_switch")
                        )
                    }
                }

                // Overtaking trigger
                item {
                    Button(
                        onClick = { viewModel.triggerOvertakingViolation() },
                        colors = ButtonDefaults.buttonColors(containerColor = Color(0xFFFFB300)),
                        shape = RoundedCornerShape(12.dp),
                        modifier = Modifier
                            .fillMaxWidth()
                            .height(48.dp)
                            .testTag("driver_overtaking_btn")
                    ) {
                        Icon(imageVector = Icons.Default.Warning, contentDescription = "Overtake")
                        Spacer(modifier = Modifier.width(8.dp))
                        Text("Simulate Dangerous Overtaking", fontWeight = FontWeight.Bold, fontSize = 13.sp, color = Color.Black)
                    }
                }
            }
        }
    }
}
